### ISSUE TITLE
Edit Lyrics Option on Right Click On A Song

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#37] opened 2022-09-25 01:54 UTC
Edit Lyrics Option on right click on a song

![image](https://user-images.githubusercontent.com/112235944/192124932-68bb1264-142a-4640-b3b2-57576bdfbc45.png)

**Comment by zhiyiYo** [comment] 2022-09-25 02:12
This is a duplicate of https://github.com/zhiyiYo/Groove/issues/35

**Closed by zhiyiYo** 2022-09-25 02:12 UTC
Labels: enhancement
