### ISSUE TITLE
Downloading of songs from internet does not work

### ISSUE THREAD

**Issue by wxguy** [zhiyiYo/Groove#72] opened 2023-03-18 16:23 UTC
Firstly, thank you for producing such fantastic work using Python. I have not seen such a beautiful application using PyQt/ PySide. Cudoes to you.

**Steps to reproduce**
Go to Search --> search songs -- > Click on Play icon

**Expected behavior**
Songs would play from the player after downloading it to the local machine.

**What I got**

When clicked on play icon:-
```
2023-03-18 21:13:00,209 - ERROR - TypeError: string indices must be integers
Error: "" : "no element \"identity\""
```

When I clicked on the Download icon:-

```
2023-03-18 21:22:20,806 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-03-18 21:22:22,848 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35ca4762e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-03-18 21:47:21,851 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35ca44f640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Environment(please complete the following information):**
 - OS: Linux (Arch Linux) with up-to-date packages.
 - DPI scaling: Full (as per setting)

**Comment by zhiyiYo** [comment] 2023-03-19 00:51
Thank you for your feedback. Which song did you search for

**Comment by wxguy** [comment] 2023-03-19 07:11
Searched 'Illayaraja' and 'AR Rahman'. Clicked a random song from the result.

**Comment by zhiyiYo** [comment] 2023-03-19 07:18
It works well for me. Please check whether the song has been downloaded to your download directory. Error informationis caused by capturing metadata of online songs when downloading songs.

![image](https://user-images.githubusercontent.com/65096819/226160013-2db7e2e4-8d92-4d5c-b3f9-f14c838dd028.png)

**Comment by zhiyiYo** [comment] 2023-03-20 03:23
As this issue is not active, I will temporarily close it. Feel free to reopen it.

**Closed by zhiyiYo** 2023-03-20 03:23 UTC
Labels: bug

**Comment by wxguy** [comment] 2023-03-20 16:31
I tried to download the same song you tried. Here is what I got from the crawler.log file:-

```
2023-03-15 12:51:06,725 - ERROR - TypeError: string indices must be integers
2023-03-15 12:51:10,319 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-03-15 12:51:14,210 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd62f7c84f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-03-15 14:47:01,076 - ERROR - TypeError: string indices must be integers
2023-03-18 21:13:00,209 - ERROR - TypeError: string indices must be integers
2023-03-18 21:22:20,806 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-03-18 21:22:22,848 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35ca4762e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-03-18 21:47:21,851 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35ca44f640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-03-20 21:51:55,029 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30a6b87820>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

There are no songs downloaded in the `Downloads` directory. 

Moreover, the song (for that matter any songs) did not play at all. When I click on play icon, I get following log:-

```
2023-03-20 21:59:54,668 - ERROR - TypeError: string indices must be integers
2023-03-20 22:00:10,947 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-03-20 22:00:13,847 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30a6bb0ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by wxguy** [comment] 2023-03-20 16:37
> I tried to download the same song you tried. Here is what I got from the crawler.log file:-
> 
> ```
> 2023-03-15 12:51:06,725 - ERROR - TypeError: string indices must be integers
> 2023-03-15 12:51:10,319 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2023-03-15 12:51:14,210 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd62f7c84f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 2023-03-15 14:47:01,076 - ERROR - TypeError: string indices must be integers
> 2023-03-18 21:13:00,209 - ERROR - TypeError: string indices must be integers
> 2023-03-18 21:22:20,806 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2023-03-18 21:22:22,848 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35ca4762e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 2023-03-18 21:47:21,851 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35ca44f640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 2023-03-20 21:51:55,029 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30a6b87820>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> ```
> 
> There are no songs downloaded in the `Downloads` directory.
> 
> Moreover, the song (for that matter any songs) did not play at all. When I click on play icon, I get following log:-
> 
> ```
> 2023-03-20 21:59:54,668 - ERROR - TypeError: string indices must be integers
> 2023-03-20 22:00:10,947 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2023-03-20 22:00:13,847 - ERROR - ConnectionError: HTTPSConnectionPool(host='u.y.qq.com', port=443): Max retries exceeded with url: /cgi-bin/musicu.fcg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30a6bb0ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> ```

Songs got downloaded in `Music` directory. However, none of the music `Mp3` files are playing in Groove. Neither it get added in to the My music section.

**Comment by zhiyiYo** [comment] 2023-03-21 00:14
You should add the download directory to your music folders so that the song dowloaded will display in Groove.
